// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAGfFF1-XT6NcE5-dYbJuJUsLMHeeFsKao",
    authDomain: "qlct-22c76.firebaseapp.com",
    projectId: "qlct-22c76",
    storageBucket: "qlct-22c76.firebasestorage.app",
    messagingSenderId: "102822327889",
    appId: "1:102822327889:web:1895eabc7b99791c43ea70",
    measurementId: "G-JDBVLFC6KS"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAGfFF1-XT6NcE5-dYbJuJUsLMHeeFsKao",
    authDomain: "qlct-22c76.firebaseapp.com",
    projectId: "qlct-22c76",
    storageBucket: "qlct-22c76.firebasestorage.app",
    messagingSenderId: "102822327889",
    appId: "1:102822327889:web:1895eabc7b99791c43ea70",
    measurementId: "G-JDBVLFC6KS"
  );

  static const FirebaseOptions ios = FirebaseOptions(
   apiKey: "AIzaSyAGfFF1-XT6NcE5-dYbJuJUsLMHeeFsKao",
    authDomain: "qlct-22c76.firebaseapp.com",
    projectId: "qlct-22c76",
    storageBucket: "qlct-22c76.firebasestorage.app",
    messagingSenderId: "102822327889",
    appId: "1:102822327889:web:1895eabc7b99791c43ea70",
    measurementId: "G-JDBVLFC6KS"
  );

  static const FirebaseOptions macos = FirebaseOptions(
   apiKey: "AIzaSyAGfFF1-XT6NcE5-dYbJuJUsLMHeeFsKao",
    authDomain: "qlct-22c76.firebaseapp.com",
    projectId: "qlct-22c76",
    storageBucket: "qlct-22c76.firebasestorage.app",
    messagingSenderId: "102822327889",
    appId: "1:102822327889:web:1895eabc7b99791c43ea70",
    measurementId: "G-JDBVLFC6KS"
  );

  static const FirebaseOptions windows = FirebaseOptions(
   apiKey: "AIzaSyAGfFF1-XT6NcE5-dYbJuJUsLMHeeFsKao",
    authDomain: "qlct-22c76.firebaseapp.com",
    projectId: "qlct-22c76",
    storageBucket: "qlct-22c76.firebasestorage.app",
    messagingSenderId: "102822327889",
    appId: "1:102822327889:web:1895eabc7b99791c43ea70",
    measurementId: "G-JDBVLFC6KS"
  );
}